name: Run Studio Experiment
on: 
  workflow_dispatch:
    inputs:
      exp-run-args:
        description: 'Args to be passed to dvc exp run call'
        required: false
        default: ''

  pull_request:
    branches:    
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  deploy-runner:
    if: ${{ (github.actor == 'iterative-studio[bot]') || (github.event_name == 'workflow_dispatch') }} 
    environment: cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 43200
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner launch --single \
            --labels=cml \
            --cloud=aws \
            --cloud-region=us-east \
            --cloud-hdd-size=40 \
            --cloud-type=g5.2xlarge
  runner-job:
    needs: deploy-runner
    runs-on: [ self-hosted, cml ]
    environment: cloud
    container:
      image: iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all --ipc host
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::342840881361:role/SandboxUser
          role-duration-seconds: 43200

      - run: pip install -r requirements.txt

      - name: Rrain
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          DVCLIVE_LOGLEVEL: DEBUG
        run: |
          dvc pull
          cml ci --fetch-depth 0
          dvc exp run ${{ github.event.inputs.exp-run-args }}
          dvc remote add --local push_remote s3://dvc-public/remote/get-started-pools 
          dvc push -r push_remote
  
    
      - name: Workflow Dispatch PR
        if: github.event_name == 'workflow_dispatch')
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml pr --skip-ci .

      - name: Studio PR
        if: github.actor == 'iterative-studio[bot]'
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml pr --squash --skip-ci .

      - name: Report
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "## Metrics" >> report.md
          dvc metrics diff main --md >> report.md
          echo "## Params" >> report.md
          dvc params diff main --md >> report.md

          cml comment create --pr report.md
